name: Deployment pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.10.9 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'hidden-wave-86862' #Must be unique in Heroku
          heroku_email: 'drecrego@protonmail.com'
          remote_branch: master
